const SET_USER = "SET_USER";
const GET_CURRENT_CONTACT = "GET_CURRENT_CONTACT";
const SET_MESSAGE_CONTACT = "SET_MESSAGE_CONTACT";
const SET_ONLINE_USERS = "SET_ONLINE_USERS";

export { SET_USER, GET_CURRENT_CONTACT, SET_MESSAGE_CONTACT, SET_ONLINE_USERS };
